name: Programmers Badge Generation

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 15 * * 0'

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Java program
        env:
          PROGRAMMERS_TOKEN_ID: ${{ secrets.PROGRAMMERS_TOKEN_ID }}
          PROGRAMMERS_TOKEN_PW: ${{ secrets.PROGRAMMERS_TOKEN_PW }}
        run: ./gradlew run

      - name: Commit and Push updated badge
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          rm -rf output/result.svg
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "📝 docs: Update Programmers badge image"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
